{
  "repository": {
    "private": false,
    "has_issues": true,
    "has_projects": false,
    "has_wiki": false,
    "has_discussions": true,
    "default_branch": "main",
    "allow_squash_merge": true,
    "allow_merge_commit": false,
    "allow_rebase_merge": false,
    "delete_branch_on_merge": true,
    "security_and_analysis": {
      "secret_scanning": {
        "status": "enabled"
      },
      "secret_scanning_push_protection": {
        "status": "enabled"
      },
      "dependabot_security_updates": {
        "status": "enabled"
      },
      "secret_scanning_validity_checks": {
        "status": "enabled"
      },
      "advanced_security": {
        "status": "enabled"
      }
    }
  }
}
